{% set version = '0.8.400.0.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rcpparmadillo
  version: {{ version|replace("-", "_") }}

source:
  fn: RcppArmadillo_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/RcppArmadillo_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/RcppArmadillo/RcppArmadillo_{{ version }}.tar.gz
  sha256: d917b66aa36779bb7ba6be8fd138ef181febfcd7e0cc093e73867f439c9ec287

build:
  number: 0
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-rcpp >=0.11.0
    - posix                # [win]
    - {{native}}toolchain  # [win]
    - gcc                  # [not win]

  run:
    - r-base
    - r-rcpp >=0.11.0
    - libgcc  # [not win]

test:
  commands:
    - $R -e "library('RcppArmadillo')"  # [not win]
    - "\"%R%\" -e \"library('RcppArmadillo')\""  # [win]

about:
  home: http://dirk.eddelbuettel.com/code/rcpp.armadillo.html
  dev_url: https://github.com/RcppCore/RcppArmadillo
  summary: '''Armadillo'' is a templated C++ linear algebra library (by Conrad Sanderson) that
    aims towards a good balance between speed and ease of use. Integer, floating point
    and complex numbers are supported, as well as a subset of trigonometric and statistics
    functions. Various matrix decompositions are provided through optional integration
    with LAPACK and ATLAS libraries. The ''RcppArmadillo'' package includes the header
    files from the templated ''Armadillo'' library. Thus users do not need to install
    ''Armadillo'' itself in order to use ''RcppArmadillo''. From release 7.800.0 on,
    ''Armadillo'' is licensed under Apache License 2; previous releases were under licensed
    as MPL 2.0 from version 3.800.0 onwards and LGPL-3 prior to that; ''RcppArmadillo''
    (the ''Rcpp'' bindings/bridge to Armadillo) is licensed under the GNU GPL version
    2 or later, as is the rest of ''Rcpp''. Note that Armadillo requires a fairly recent
    compiler; for the g++ family at least version 4.6.* is required.'
  license: GPL (>= 2)
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-3'  # [win]

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
