# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "EZtfG5Je8Ch3Ht+atLviLcKjX8JIFHRC7j18oTtgZnoBj6V+VE9JeyKDJz95kW9Zze49ag/mn6CxLChlGyJ4s09CQsME5rQCagik2UBFT7po4rk5KdNgXQnSwetT2wYItDDzq9DfCqwljFljaK0d5+0Ofx3+IvGxhmRiP9BaGEALZGu+nu5xbxgr33ufKmVhIcB7kYLSQc//Jpz+DVUiV1sGFo9QuZAThoaiBUMCCYNUoMPxmGSN7UM66xLfsnMtqKyGeCPPymEX93QC0PbJ0PPCakgMVYuqHHkIx5wlk2UiN6hJBg1lW7QJ96JPVUzNhCrK/RdNWsAJkV3M0yHXKBjipxVoO11JRPdAgKNw1G6LcceMLOOl230vkt6fz8Oo0/8/DTtPGxwSQYVAULtWnFElwCVfqBap/c768OM5BvTHF1Ek+Ug53BD5zLj+uqdA7AHo6rfEOG8cYxDuXF6EhCnLe39g9C5WHKmpfRWojczPqM1R37l/DpZUKE39Ad3CZX3UXqqDZrx6sliQALKFfrkBtCC3cBTOhWujYEKUcZR4+CvzFBuud56L4e4H2m5U8jJufO1LqMDH4TnujhSRR74Womhn0La3SO6KMN8OSDK9wP9VeCR6nklVkjwiOPZ+qJpLEEwQenHKldaW9N/vDLBvlhwGb3wYG6cw6sz2QYA="

matrix:
  include:
    - env: CONFIG=linux_ppc64le_target_platformlinux-ppc64le UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le

script:
  - export CI=travis
  - export GIT_BRANCH="$TRAVIS_BRANCH"


  - if [[ ${PLATFORM} =~ .*linux.* ]]; then ./.scripts/run_docker_build.sh; fi