appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  linux_aarch64: default
  linux_ppc64le: azure
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: EZtfG5Je8Ch3Ht+atLviLcKjX8JIFHRC7j18oTtgZnoBj6V+VE9JeyKDJz95kW9Zze49ag/mn6CxLChlGyJ4s09CQsME5rQCagik2UBFT7po4rk5KdNgXQnSwetT2wYItDDzq9DfCqwljFljaK0d5+0Ofx3+IvGxhmRiP9BaGEALZGu+nu5xbxgr33ufKmVhIcB7kYLSQc//Jpz+DVUiV1sGFo9QuZAThoaiBUMCCYNUoMPxmGSN7UM66xLfsnMtqKyGeCPPymEX93QC0PbJ0PPCakgMVYuqHHkIx5wlk2UiN6hJBg1lW7QJ96JPVUzNhCrK/RdNWsAJkV3M0yHXKBjipxVoO11JRPdAgKNw1G6LcceMLOOl230vkt6fz8Oo0/8/DTtPGxwSQYVAULtWnFElwCVfqBap/c768OM5BvTHF1Ek+Ug53BD5zLj+uqdA7AHo6rfEOG8cYxDuXF6EhCnLe39g9C5WHKmpfRWojczPqM1R37l/DpZUKE39Ad3CZX3UXqqDZrx6sliQALKFfrkBtCC3cBTOhWujYEKUcZR4+CvzFBuud56L4e4H2m5U8jJufO1LqMDH4TnujhSRR74Womhn0La3SO6KMN8OSDK9wP9VeCR6nklVkjwiOPZ+qJpLEEwQenHKldaW9N/vDLBvlhwGb3wYG6cw6sz2QYA=
conda_forge_output_validation: false
